import { StyleSheet, Dimensions, useWindowDimensions } from "react-native";

module.exports = StyleSheet.create({
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    textAlignVertical: "center",
  },
  modalContentContainer: {
    width: Dimensions.get("window").width * 0.9,
    height: Dimensions.get("window").height * 0.7,
    shadowOpacity: 0.8,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#2086D2",
    shadowRadius: 10,
    elevation: 1,
    padding: 10,
    backgroundColor: "#ddd",
  },
  modalHeaderText: {
    alignItems: "center",
    alignSelf: "center",
    color: "white",
    textAlignVertical: "center",
    padding: 10,
    fontWeight: "bold",
    fontSize: 16,
  },
  modalMessageContainer: {
    alignItems: "center",
    justifyContent: "center",
    color: "blue",
    alignSelf: "center",
    textAlignVertical: "center",
    margin: 10,
  },
  modalMessageText: {
    alignItems: "center",
    alignSelf: "center",
    color: "#444",
    textAlignVertical: "center",
    padding: 10,
    fontWeight: "bold",
    fontSize: 16,
  },
  modalCloseSuccess: {
    backgroundColor: "gray",
    padding: 5,
    borderRadius: 5,
    justifyContent: "center",
  },
  modalCloseError: {
    backgroundColor: "gray",
    padding: 5,
    borderRadius: 5,
    justifyContent: "center",
  },
  modalHeader: {
    width: Dimensions.get("window").width * 0.8,
    backgroundColor: "#2086D2",
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: "gray",
    height: Dimensions.get("window").height * 0.065,
  },
  image: {
    marginVertical: 10,
    paddingVertical: 10,
    flex: 1,
    alignSelf: "stretch",
    width: Dimensions.get("window").width * 0.7,
    height: Dimensions.get("window").width * 0.4,
    borderColor: "#666",
    borderRadius: 10,
  },
  button: {
    backgroundColor: "#2086D2",
    padding: 10,
    margin: 5,
    borderRadius: 5,
    width: Dimensions.get("window").width * 0.2,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: "Avenir",
    textAlign: "center",
    alignSelf: "center",
    justifyContent: "center",
    color: "white",
  },
  padding: {
    padding: 5,
  },
});
